name: smartpay
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
#NOTE PACKKAGES ARE LISTED
#ALPHABETICALLY
  country_picker_plus: 
    path: ./package
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  dio: ^5.5.0+1
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3
  lottie: ^3.1.2
  provider: ^6.1.2
  flutter_pin_code_fields: ^2.2.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/svg/
    - assets/images/png/
    - assets/fonts/
    - assets/animations/
    - assets/music/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: SFDisplay
      fonts:
        - asset: assets/fonts/sf-pro-text-regular.ttf
        - asset: assets/fonts/sf-pro-text-bold.ttf
        - asset: assets/fonts/sf-pro-text-semibold.ttf
        - asset: assets/fonts/sf-pro-text-medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
